//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuleEdit.srvEvalPersonaBatch {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvEvalPersonaBatch.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EvalPersonaBatch", ReplyAction="http://tempuri.org/IService/EvalPersonaBatchResponse")]
        RuleEdit.srvEvalPersonaBatch.EvalPersonaBatchResponse EvalPersonaBatch(RuleEdit.srvEvalPersonaBatch.EvalPersonaBatchRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EvalPersonaBatch", ReplyAction="http://tempuri.org/IService/EvalPersonaBatchResponse")]
        System.Threading.Tasks.Task<RuleEdit.srvEvalPersonaBatch.EvalPersonaBatchResponse> EvalPersonaBatchAsync(RuleEdit.srvEvalPersonaBatch.EvalPersonaBatchRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EvalPersonaBatchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/HelperBRE.SampleSubject", Order=0)]
        public HelperBRE.SampleSubject.Person[] ArrayOfPerson;
        
        public EvalPersonaBatchRequest() {
        }
        
        public EvalPersonaBatchRequest(HelperBRE.SampleSubject.Person[] ArrayOfPerson) {
            this.ArrayOfPerson = ArrayOfPerson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EvalPersonaBatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/HelperBRE.SampleSubject", Order=0)]
        public HelperBRE.SampleSubject.Person[] ArrayOfPerson;
        
        public EvalPersonaBatchResponse() {
        }
        
        public EvalPersonaBatchResponse(HelperBRE.SampleSubject.Person[] ArrayOfPerson) {
            this.ArrayOfPerson = ArrayOfPerson;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : RuleEdit.srvEvalPersonaBatch.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<RuleEdit.srvEvalPersonaBatch.IService>, RuleEdit.srvEvalPersonaBatch.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RuleEdit.srvEvalPersonaBatch.EvalPersonaBatchResponse RuleEdit.srvEvalPersonaBatch.IService.EvalPersonaBatch(RuleEdit.srvEvalPersonaBatch.EvalPersonaBatchRequest request) {
            return base.Channel.EvalPersonaBatch(request);
        }
        
        public void EvalPersonaBatch(ref HelperBRE.SampleSubject.Person[] ArrayOfPerson) {
            RuleEdit.srvEvalPersonaBatch.EvalPersonaBatchRequest inValue = new RuleEdit.srvEvalPersonaBatch.EvalPersonaBatchRequest();
            inValue.ArrayOfPerson = ArrayOfPerson;
            RuleEdit.srvEvalPersonaBatch.EvalPersonaBatchResponse retVal = ((RuleEdit.srvEvalPersonaBatch.IService)(this)).EvalPersonaBatch(inValue);
            ArrayOfPerson = retVal.ArrayOfPerson;
        }
        
        public System.Threading.Tasks.Task<RuleEdit.srvEvalPersonaBatch.EvalPersonaBatchResponse> EvalPersonaBatchAsync(RuleEdit.srvEvalPersonaBatch.EvalPersonaBatchRequest request) {
            return base.Channel.EvalPersonaBatchAsync(request);
        }
    }
}
